language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt

before_script:
  - export APP_SETTINGS=project.config.TestingConfig
  - export DATABASE_TEST_URL=postgresql://postgres:@localhost/users_test
  - psql -c 'create database users_test;' -U postgres
  - python manage.py recreate_db

script:
  - python manage.py test